data:
  test-path: datafiles/test
  train-path: datafiles/train
  manifest-path: datafiles
  size: 50
  round-power-two: true

dataloader:
  queue_size: 128

model:
  d_model: 256
  n_layers: 2
  d_ff: 1024
  batch_size: 8
  lr: 5e-5
  n_epochs: 50

train:
  compile: false
  clip_value: 50.0

profile:
  is_active: false
  profile_log_file: profile.log
